spring:
  application:
    name: yudao-server
  profiles:
    active: local


--- #################### 芋道相关配置 ####################

yudao:
  info:
    version: 1.0.0
    base-package: cn.iocoder.yudao