server:
  port: 48080

--- #################### 数据库相关配置 ####################

spring:
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 127.0.0.1 # 地址
    port: 6379 # 端口
    database: 0 # 数据库索引
  #    password: dev # 密码，建议生产环境开启